---
kind: pipeline
type: docker
name: Default

trigger:
  event:
    - push

steps:

  - name: generate-tags
    image: quay.io/natlibfi/drone-gen-tags

  - name: audit
    image: node:14
    commands:
      - npm audit --package-lock-only --production --audit-level=moderate

  - name: install
    image: node:14
    commands:
      - npm ci
    environment:
      NPM_CONFIG_IGNORE_SCRIPTS: true

  - name: test
    image: node:14
    commands:
      - npm test

# Not enough coverage
#  - name: test
#    image: node:12
#    commands:
#      - npm run coverage

  - name: build
    image: node:14
    commands:
      - npm run build

  - name: static-security-scan
    image: quay.io/natlibfi/njsscan
    commands:
      - njsscan dist

  - name: docker
    image: plugins/docker
    settings:
      repo: quay.io/natlibfi/melinda-record-import-transformer-helmet
      registry: quay.io
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
---
kind: pipeline
type: docker
name: Update dependencies

trigger:
  event:
    - custom
  branch:
    - master

steps:

  - name: publish
    image: quay.io/natlibfi/drone-npm-git-publish
    settings:
      git_user_name: natlibfi-melinda-automation
      git_user_email: 65649125+natlibfi-melinda-automation@users.noreply.github.com
      git_ssh_key:
        from_secret: ssh_key
      git_gpg_key:
        from_secret: gpg_key
---
kind: secret
name: ssh_key
data: /0HOXHZAZ7ZA4HFrST1boTw7I126EHBGK+/MTWNZpeuC8EkEge8ilx6NG2TDuIfNnjZkKN7wD1G12Nh9akx7VxfPIFixAuCOOrZTc9U+ZpQ4jIViAFSQu7a1IIxq2/nlx0uT6Iw9z4LQorPLpZfTu1JCaS5vq9Vw5eH9vOoazVWaCoAbZ0XRPnXbcqgpJvK2ajrihZgfK+oeF+2L/hggMUe3kh39OGPWeinle0SK9JV/9HF2ITjG05vfI3Vfq9AxNPIjD1n2y11hjwsKZiSckaUKcIPBMEC3fIZBrghlGUwb20kxLPK6Z/ws9spYoQtImoUd2NIKjsYnQE4ZWE7jX/m51xRmKjAELdIv7gi5YBDusenx4BU4mkDqq7k2pUQERj0fI/Lc1BgAJW2QetHlIrvWnpnhDis8C6/8NLJ/EdcDIQHhDvOlx1WC58iJanLuDspQlOpnO95tC08m+zKgDuf5SNVKAfrAE/mF6pTaHNYer9qcOIqtX3cbEe+Ku1FybA7iYfHRs81fjsZQlGSWb8eQxwVyrIKnh+4fRxHOHHuFOc7wNBwoU8t7iAu7QXksMQdPp2Q+aLP+SuA/DxMiHgGsRe5w433cF0Zm4nE/BADuuUoTD5cUy+fOeWRU1hihdVRt+GYRs7cUUWpyHWy3hc3Fk/NnMAolqvvNjoVr3WoGjIWHUbcFFW47Z2ShfKF5OV4hjxmOyB0vI/KVTymiAOgNPu7E0uMiycAXti+pjwPDOSK75j/BsQ3kO3m+pEuKLAtb4mrs8SXrj673OtpxMMRDtDQbgT9ENuYFCLnLXEY9v5LCPtAJAjKsMfERumhMZPou/W/tXnTxOgWe331HIKX5o62SSqRWxJB4cJ5lMIWkXpYYjUxa4hNr2DWnyB/6cVxYQXRvbEdbDN39lWfleXVQTBQ2k7hIWXIy3i5N4TxSrby7+48WMTBs7TO5qyUe42h5NC1u4y7yAsP57PHV+D+FkPDJhRSxfMAD1IZZY92QFjcfNi+u2kE1t4iNGYvIvSrYNxnL7rtjkdP6QD5XEtcKtk7FLoYr8k2RvrnWhOiygD4CC7MABR9r1xlkIfQNBF/Sy/JHp2YvA57AZC+fNwROxVzx+mLNfwI2p3MVl8sqpINMPTMxhBH/H14U9hmiqNwCGji/JJEHq84Q+k19Jttm+yTXUMyNWuKDGMYf0b+yXz4AdkaIt6h8NxWTYZm04lStbiCBC+8O3nfkXV3EpcqEqmkVQaVPQKTiTg7HinOXnpk2siQwySG5DX0FnbdVolT0/R/yQsPKO1+Yra5KMsIOXZmH8/r36WNsIuKlBcJz053rLbS9qlX2+w5zaBdj04tQngZmx55YK8VKFq0V3lF4asrBoQnXgOdjEjagbopvbBzwg0glCRCor6aHJd2hj8sSkwyXmkZ1XFPdbyl9EikddNqk/5fIB3LRQPLOhp0b0ACL9elrP7sazqnv7rEdnfC4gVZt8T73s+AbSCwhq5eugY7zG+OezL3oit4g510PooBLeS6MrHtmHyet1KerHqfkpgVM/s08C7MhO9KRY6Is94+fqwxwdF390TG4zpuypkK0a8ixWrqIWtdISqsBQiPwIGdOGaY/OIWchX/Svf+5jWRYrb/1putOf8eRczYamoLCRFRSHufXKN4pxr/2nk31vtZv8fc4O6nZr4u2MphxFA75WlJufAUy/KmBH0jDmbPghb+kSpfTzXlgTvya/Xp8ouLz2tnmXfSpFVdt4aDm5dAq3zW6kYgUSQwCJxbRRxUXC3Yvvgwp1IjUnsGKi7UibR116YGvfZ/BGlohfQxLsZpFV1/mQpLiC7duYMrzX7KSvlIrBTYF1cLuUsFDWdMFIZeEpx79bUgWmYno7hI2evxJb8s1VCqt03ETEbwMlQDeNKn+qEsH6J624Ge+rERIbH3hHc/BxkVC+0h2k+Z4BKk9er1k4ygQ1S3nWzLUfT0XGIoAtbKroUUYT2ss8TfnqEW9/124xAXoyeFg58PMj+yO0DbN3IlC0kGA1oq8UwIOXExXrsdCMQn2ty3USRg2nJ+3EQgDcOJtEKqipwFSZiuKte55FyPcjjmHExnSb0SeqiOuntE+ZIMtpaJeQdJuqjidgylTx5HC7b8qCKJwtYvxvmFXIP+AMaGQu00icmvvk79Q+jotbRWbJLI+NqdZcz1zbeVU4Qw1W7I+bViRG4A2N6hbZvFNdj9Py85OiRaeJJZIf7N4Gy1yvajg4PfoUwDGqb90nCh4iV19N8kXwKEz6phJWtdAFu+SV1nNnRHR73FlRAkDclwk2XTF3SMnjZyaBAUS7RBfbferK15WDiwigc68JhwsZqOvJ5Q0YuKka5rALPW67GF1Sgjx2R4N1lcfXGcfy8qjDRSghzAzm86rpKs/3YN1Gb6purrod08rm0E3D509vPhZ01oeVX0c5YBzx41HqeRYqIX4R65rmA+D09fqpBSxT3nT1MYAYwEVvSh0NoGP/6w7ok7i+D/7eRI953sEqM8E1y4ThBcLRv+Y1LlqJzfcOi/oYoAJ3YiBjFnVClPs/TBZPGARmoDr/VBH9urj+B7SA/00cTNiuXggwTDvhkLi3xGKwUOJUuG8g76KckF9J9aH2Jv6rlNcVRq1PjBD05ZYE9wC7IJg3UjJcs3vPx9pImTxJUpxUS0LriZksGCMEHPK4y846R8JyPmO/WPVf0O41kpFxmsPsGsoWrgMowCb5T/TNOMH55f+bicMsvjXoK6Hhim6sK/2uO2dSb1SfMyWnGYNal+l3jAe/BjlxwwPtxKp7Iwne512kz8GNuvsTZ7h5dtaCQIFeiXdLi1KjF/okkqtSMFwhy4PN0bRwO/CdJ4PuHGZ/D9QnBtA+Pp8M8NqwVKaJFuopZBlVDNgYNRTH4sXXdKZ3oW1RAdPcx4U6NeYeMo8qodJlKvIDOvfYrF2edd8pCnk1T15u5FO2VJho6qTYX7KqeeWBqIaoG7gzShGdBEBGlYYgqx7allg8oWuBYjGqw90bAy/F3dWXVjm
---
kind: secret
name: gpg_key
data: Uxg4s+BQm3838LYhrVB2OWLnCkRpE8/v9WM9/Pbpt0cY4x17hE2kcbuwypYxcM85qWLifYCrgCa1NCq5fmShTpHnB99AD9IFD/C9vVJ6FS1pWCjoTrDueL1Xj/8KAaauT3x8NJiLM3wYdCnA0wKa1CALuPYxQLuInkhOxoyfPddzIXi5mVW/yY7jhrYlufa2VE3UiqRFa0X3Nu7iH2JlVeOodfLanpdDlu/61SdlhO4qD7PPESWRHcLL5cRoKN7QDkIKFRa77s0awIw1FqNebWDR2XGExbPROBc+/ewehCpJFWA60b6SCikFEB5FYkD+ngAhaAe9OxBIvmk97vRgj6sLqzQ5RA6mkQrkatiLz/5oCQDvz4dPquBOnxDMorhZEOgXrXso4skYRevmNJ9mqGNJjMB71qo4Sa77wz7WD4Uwt/YzC52MBdDxb5YbcBJRvh9vDF6S9FCqiIb5yO/CTdPWIKrP+WC1H5tRlKtSVmFOpW66oszrlK3ezVtZhiClHJb9lukzHwmkyspjxj3bKVVOb2TFn8qZrViLLBtO1DNYREXLeO+J9kshBBUDkEohQI9Cysq6J5I4LcX320TbUi/OifPMXbTFXkiUj6LlyJjHMp7MWoUxj1diAoCqaVpeZh7gg9wSaNZT6iSZMHw+4aDysrBjfmuEFuY9RdreDi23dEoy/jXQyFM8a86P+Jxg4oIbh4vnVBCbwa4dsr25Xs/I84lxe/+qyCjL7yYqqSMwWLWgRnjLouSnqtuoNozjFxHRG2Gq3gdSA+bTd/+49gGTA/fJFPOvoPe2K8ty0w8jzsQMXws4DUn9RZ3Df/iAKBYnyMh9ec8KgNMK31Sh3zi4HYxZ1fng78Dsrxn+D1RqXmtwmEM2fm+YusPNfpB1ATbZonpJ3uHeMRssrMzJeua9DBrLHMJkWc+gDyIVkZnWK08qDfB9ipGkYYd974BqO6Aias8cdlC9cRvJyFJ7ZRVT8pRV+JxazcOyloz/MVuaTj5htJQaVWv1d+hpxjzCWjBdNSwZLE/hDVs++ezszdfmRQ8qLad8QOt64QJd6uf2gMUfK1pJfrKQdAMvPybkoMnz+9pOPDfQvDVj08Qs847jcggKSLliWZee6mKH1KWK3sghNFT9ZevM4Ib1Q7L9z4gRJYWlCG98LPDkYnaqr5kr97nmJR4UlXZ0QkMfAjmnCZXIcEvqaW/R7jzFln6cPzyddWUhfzzCVgJFkYOgYlSpA/IhQ5J9Ti7XimGMfgvygipaBPKgEwkTfcBkxn91bKxQVKzcnYAJnpTznaau2UH9FTO1ZyuC/bjqVgCWBYHMkmu2YpldA7fCTaSZwL4/mZVHzzbMT13EFcd/HyJvZO0q7LWx/fP8ERrW0rszWf/wJcOOq6/QkdvWJMAHjUjVYRFR3gXvqHGsl3sAyAyD1G7SoZEMjxuw3YQZiYUzoJKj/kuY3vQTYBJQ18Q0+4CIdz4om1jLdNp4PXkhHztUlIaqqQttLFtAfVXQXqciMCzXKVG6kAcP5p4CBEd82ynZFUPQ1z/t+L71zL9kiZIYp2KSofKppsPHJhAebW2gQyq2Trcw1VbZJWwNzlihsXAXzUcMNp4iLocv2pjGyTbYrudUEoyeXv22/zxMAY38EihBpb6mMCcwhKOGNExcOZmZMuBq1Y8f7WgOw684b02h4+5BPcADEa1Uv0yelOEE0A76EKIT25NXaO8FcEKs+7ej/k7tRQW8yNzgR/BUP56919NPgxDovIDnd1I4IXK/Ue7sllqrk/UirlVV+j+ncnSDPMd+CQNZjvbnG75br8lUAp8arg5qhGUYU1JBtvGyXl65Q2GPQLKwFcCw1EmBoXiLwbZbvepHq/MNy1XxQNuRUcxY4Wbd7Ug35oVY4AVJh/s2yZs1L4NO8Juxa7UZe3pRJ1X77PguY40eQrjybViou5y0N14MgM14v+xygZGyUAQYsk7UmdKI3D9xT7l+865VR//tb8gLNTlhE+0JXnmhivo5PYOt1d+yQaMNCH+wbTS5RDxplflAwxFBpap2ca+99+BggqgHmI5Uvw6lEh2ZuPEfGZW0zI8kZsqQyZ+20LpFk5EJwjm7AZlpycSlQXUFYEnv1RzEHFMrQOh2ye+1m7U1TMzzb/ihULmzbZ5PAtWkRoAm3TVAnadlJ5uqgkWIswTrBDCHi/1oMVpZaRc/jY6/f5U4nLTyPn9ytUpwxcNnetkV1x5rWVJdzr6fF8vMPud4WSQw5e23L1wgcifPVxMRsAqLwP+2sHoCg/8tePaZWDAEHt4CxE/rzKBgMutmO8qlRA/6yLvZtUWU5YbRWxhcCn2bjVialJAYE3Td1cuarZW73OyQ9SNX1h/eirco8Uoea4hrxquBJMRVfu/bPd6qM5vHb4SBxX2ILxuvYTof3dNXI/m1DszBGZb7LkAMtU8a+0YbBCTg/hCZZHjWe7ZeiSjGRxku4YtayIWR2ak0b6qc1CqqdPqx1537hiuFnV0FQsOeR6ClMj51d/iZApp/K2TF7Ci+8JnPmF1lqpBHHVOCp2AXNCMbNVeWpJh1rjYg2L+fAiPnyYMDIEwCTU8TpCbirvW97CJsRA5g7xuJNdfrkXMG4Rh1ZL5ribJvCSR49V4sTf6yPRqspcfZ8+KAj/i7DEZjTM0KeGkBPVOZcv7KfmdDpRZXkKHuFNYFtc7Wo6b8/UFMhcCpYGU/JDXkcojks7hrDTFwLDx0pLS32MsGzyqzAD7i2jGSPYHqgsBeGOQSArp8f2eLlezNLc/AuCjZXfBWkD8pxPxp7g9JzyaX2bsUVRygXvr4teDyJpRbzNmzm4b7HK5SOjOOQ7Y5sWbu2G8nCdbAVjPqvvVFJOg+hBxnmZd7FCul4cdciH+yTb/TOeE5q/iMYyzNzH/EAzF5GKQVPk6Z85FAJjM+AdDqWFRRqa8dt7JvXZ2G0qGuECF6341k8PsgES7wqKKhtpegEJv6FvBmS5Z2UaER3y0Wq+TBSmsO/9tYN5QPLpe3Qaj4eQw//R44uS1QSp7V0SfO9RF14ekO8mWjZ61oUzNcCIftgRNtwenhnnPg1Vl8+dJhxAkdi7Jea7nqZ+0KZL5EHvBLgFqBIQXlMyjSwwtlJgoRKgPde7Diz31M+PrvvN8ygkg+PqcD2V/FlPsIAN1Xbt5bABU8CqlMin/tdC/f/knMuB6Xx0sYNpwGoWSplsQg6DjRGkPL3oe1badaysHgmvhM8KFZJWo5jquaTZsmviY+hjVxTqbjIsBBU8SrTXKsmtvs17Ugm3YPQMR9fKVWNk4TuV2cWyDsUkfrK1BpgQLd/ugzoSudEuoIVJTiAY+6c7vzfTuRUea9gLlMxZP/pe4ZlZlfKobkwSkX9UjJmLNp9mGoyoyCnPpHZNcUfXE5zER5D3vtwu2burcsBpesj6bFZh+8UkUK0iaVaXxXKeVP6aTg1+29u3aStM1LvqjUCyCQXyboi+0lAPiLuH984zZ5Tq5Q+PU8jqrYCGX8nCwYP/ATzousXVVSes8kbJVTWKeSmeC7ZK9cOcPfdhCx4DPOJYZBuNVfp4/uCHZkh+AFeoS0yyTkwishKfSSO9Ob99Iyf2RTzv18r42moY70MfZnf+gDUt0xmvoKI2nkjZGez9EPQkAH+EYOIflX2Kocb8Msy6auRND83fUk0fBYegBrk/CmdkCWkCv9CwXlSxAZSFHg9rRAPTNqTBbsBUodsMxKro/g1yMOe/Po5dLJYiDIIpGrqYccyVlj+4woj5goiNqeVFOYNDMvLW0TPEX2oCDqq8HWeVeGCDyu/lvnn+J2ZyBlyrAINoeKuzk6Yc8e+C/BjGVaU3fNBcZFiPDTGsSogzFY69TRNqGedo1jRmBt3ze0VaUszA/HEPWZxcCT4Iyb0j+MUJkZHayxmxj8L1zs1MGMxrcIBsppKPlwEE3V0HTm0JorR49aaHMH/iK6k+r11z/IosPhLLXxy9ndH9Xln0d7n7DX4LvanL5mHubf1KKn66j/moI/Cp14AR+lPwygDhJPXS+ojrky2w4LGs7ml+TPVBmIk4Raxin1uNpa8u3Wz643x1kbMFJ9/m//OvgKXth7+bPvl5NEpgTUXyLg2Q3t8Hca7mJxgNN1VhdzA5JfKro+KFDr/nxeoqF02XudrTdsUHGGfA0jJFsZBwJpR0JjIpsjW0NptL0Ynvox0WB9Jgmo0bvR4bB+ByIwbY4LbTdAYT4p5j5x3SuUI2vFm4E9ZWaM16RQVvB+r9EMR5SwVtcxJJcS3MUnTpmdIvZQ0RRg1eG9gI/X8Fu+RUJ8Gl+YH9pgNFUCcVOTTOddG5F6pZ4lawHA4AAwpO6nGbq5UfMngQwWkCdJXLFq9/5MhxkoliqoYj8vTDkgdUSlMDM0sVDAcVCEGBXLu109bg3vxTIfKXkQFtlzB1avSnrnx+vA8zKwRj4wgteZ0BuggbQOX6PNNR6Iy7n1RNNoWAGNmeEACPAwEn88f282YTe4N7ZUkfUgT4ehlQUIAD3UuvW9uPd2YvFnIUY5W2B5UL6sqDLys6NqzPHv5iOM8yngOkTw5gvbL1yB9YD0GfxbQaKjMgyUELZMI8Jw8JEdFMu6LMgKy9MJTlDBSLJ0em6sP8lVAvMBeYVCgp9TmCG4lJN4IC1hROn0RApibsJgUPwoGf9lf7ZMZZj5swArfDcgzgtZ30UNZMypaFXh0y5mB25r9qxQMs9XcfIW/MB0LXxG5nAHGY99C0Wf9SbimIK653JOCvrvOtsPch+97nptPKd1SCRd5Y8lGEltp6g/vQjs/yiH1ZILUSYO8gSZjZcDX6ZhpEqT0RP87jHJP4G3C8Xn0SoO6Yu/QIo1JD4xlDPc7ehmOMXaDg1qtqWCdP0qMEC9VjFNE/UxvVF0736glEhvIJsLLQfFtTV7DuS02cACZ9E7AhtpqOxvTlJmxIsdd/OpGfjIJw+m+KkVoph7ODi7yPL2a1/9Wt9VC5CXMFZuH9JSMSr0OHbNkDMVR3O5xm3iWClMXg37ocDMvmbCz2b74QIdIKzAFwcAvMZSnqY4p0hZsDpJM4+1NuldnTA4NSdb9xmEOT3GprepgmAKBaxrpHW3Qo8F4t1rDRcUCw0oe04ygWu6DfI4DRA+w8upebahFgBp/lpTtDF0tF+kXyAkGTbH7tnYizTIg1BcBtAV0An4M6400hTahPjuit6dNAy/pJfO4Sz/H4bHhdl8nOH3BcQnWS9L/8IQUDst7MKZbMWhxvXkSdWKQYlcJDBr+iZf9CwO8r7WxQCXrxqIaXSiQwDUG7fSHfoboVtd6/2yjT5RHdOwZCAwSfwACIoCcXjJMkzRndoFBRePQIHHNpP/yK1jhwote2eW3d84h54XFdEZlCGHJBtrrqlzw5v6NbpvJcIBbvgwQiGt1Yv0SoJtXSTpczA6liU8m91eVgTtMmSi+q/TRNROxsDHYAjDM23fvh8D4ynvqA85Z0Bv5tkZB0jUzyt7GspmA9DeoTXiochqX7w9QKHaeJpT8vu5LJxIXBqSKgUZVo7qptr3GVRU8KxZpyJo5+WF5iK3107CK04WjQZDpMgo3Z9+g6Y6PTwZpCnQiNqsstXeI4ukos3Xg78eJ/ZHFkaJVZD77i5uPOVY8BG1Esg/ilfuwGzAvCuI8YpQSZcWRumgoNEQBwd1MRKcTzFF2CKxkUVd9k/jUuw08Z5/JPqlm0ZgiZRumonjlYPZGDQc5rJd96lI0MHtAQX3FYw6elUnf14x4RP03FzBp+G1U+e0BorS/hJbyhYCAJgC9sQXdbKnbwBeDyFvRwWJLR9yRF9UriaRYvvPOIlccHbxFT5U8aVkPGfv59pD1DbXdtfNYLn9KulE8AJOcYuL2c8nX7SDonj62eJZmQ8ZvRvlYJ6J4bhTnCCqFQlgaALnPR7YrbeIlQPGnhdbROb6g6O1PER7KzqiZBFJMVgIDd+FSSDN/4kEAv+rxEtEng8kcXI9F9DP4ukJ0vgiulPan9FeU0bOzAgTRtNhDGtOPdzrrA+jgis3iN0oUCO8aSNPdBUR6hFuCTakl4pM8z4h1O7E/Ge0ivfr7oHXkq6/kDv6kW5tOVM3Nr8TQzOCgM2X4Y2JwJRhd1uNsGQQohDA3Ts/5lzvfS1lOeDpJwMsMsR91LUVgicg3xPRPVeA0nj1BjoWYVySkK34tdf96bKV6vX4+ec9mE5KKEg80K6TtFY2R95ber6lAfmvstdBwUFBG3NGZD1F7ggSVHMBXKsMclC6/2RIzZ92c18hwzfTDyd/Y7wiFAk56MROI/DipO/+QIP0056xYGQ3zKNCoddNoq/ZOvCicHcxtR7yLasgGDIIsXJ9Zmgy5FezjPAHGriJf828vkV8AdLFn3rZhHiquN2tCTesYZStALdzMWDttuMmpGZeTACqNd2V5Cc6Wk4PDaPOVUd+MKKlG+rTrHix0Ki3gEPKYtGATg7VoHp6atXtekzS+TtuPw6DkTpA1ELcUjDeyEj27H0bRr6xHEYPsACHhNn2Uoj8JThgB++EhIuzss+vk+V63swoDwHqJ3Ivdf3TrhxR1MjDJSHxiLVDFWWCa/MaWbiWKLCPkgRDlbElPCAM7scWZH3QrZBdtTC18P0M5eup4jJV8aVZLQfyS9gbHExEK3qKbXceoAsKEYlU0n9Rj/i/Ib5uY8qzVnQ2CUa7S8Kc0FGv2wLCfKqTCMvW+cbylE+jNw==
---
kind: secret
name: docker_username
data: PVcqDL0FcRVxnosmQgApdd8ydOi2G5KPyl4sj+wiBQFw1xPu5nVY7S1wMbG5DxIIl8M=
---
kind: secret
name: docker_password
data: q7M9czMgHZg9fRjxpp1deysM/fT8b/ZGR66RRaXvXakGGbJxmuAXk7cylUnRbj27O/baPgcw4L/v4jGkWjIht1QO0WeR12MVdJg50rLsIYtNqCjAdunZwQGBZL8=
---
kind: signature
hmac: 56696ac750e1fddf27063d76f8d5fa45d88da1a9e355ddaaa417fbd25c8295ca

...
